{% set version = "0.2.1" %}

package:
  name: xlayers
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xlayers/xlayers-{{ version }}.tar.gz
  sha256: 7f2581fe681ddaa59cc56b933f02e134ccf04bcd1d339243986f8055e4cb548c

build:
  number: 1
  skip: True  # [py<36 or win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - python
    - pip
    - numpy 1.16
  run:
    - python
    - xarray >=0.13.0
    - dask-core
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - xlayers

about:
  home: https://github.com/cspencerjones/xlayers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Fast convective parameters for numpy, dask, and xarray"

extra:
  recipe-maintainers:
    - cspencerjones
    - ocefpaf
